# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenSpot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenSpot
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Phone'
pod 'Firebase/Firestore'

  target 'OpenSpotTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase/Firestore'
  end

  target 'OpenSpotUITests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase/Firestore'
  end

end
